### ISSUE TITLE
Uumuu fight feels like RNG is manipulated

### ISSUE THREAD

**Issue by ianw11** [underlein/HollowKnight.SpeedrunMod#2]
This isn't an "issue" so much as a question.

For the past few Uumuu fights, I've seen almost all attacks be the "fill the room" rather than the "chase you".  In addition, I it's appeared to be 2 Uumuu attacks then Quirrel instead of 3 Uumuu attacks.

Has the Uumuu fight RNG been manipulated or have I just been getting really lucky?

**Comment by underlein** [comment]
The Uumuu fight is not changed in this mod, however what you described matches the Uumuu changes in QoL.
