### ISSUE TITLE
Make the mod available to download on Scarab?

### ISSUE THREAD

**Issue by Xen0n9645** [underlein/HollowKnight.SpeedrunMod#3]
More of a question than an issue, but could you make this mod available to download on the Scarab mod installer? I don't know how to install the mod otherwise.

**Comment by underlein** [comment]
This was made 2 years ago for the modding API at the time, and HK version 1432. I doubt that this is compatible with the current modding API and the current Hollow Knight version.
You can find the binary file of the mod [here](https://github.com/underlein/HollowKnight.SpeedrunMod/blob/43324541d3bf3f0c3841d6b861f3a81a01c7602f/SpeedrunMod/Build/SpeedrunMod.dll), if you happen to find a compatible modding API version for 1432.
